### ISSUE TITLE
Doesn't work on Python 2.7.5

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/s3am#14]
The work-around-dots-in-bucket-names code tries to monkey-patch `ssl.match_hostname()`, which boto will later call into. However, that function doesn't exist until 3.2 according to the Python docs, so Boto is presumably using something else on lower Python versions, and the monkey patch gets caught trying to patch something that isn't there.

**Comment by adamnovak** [comment]
Apparently it also exists in 2.7.9, which is supposed to work. So maybe it should just refuse to install on 2.9 less than whenever the feature was backported.

**Comment by hannes-ucsc** [comment]
Fixed in 36d2c3d3e8d72eb116c5879bed1020e54dc52112
