### ISSUE TITLE
Add Feature: "Force" upload (or change --resume functionality)

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/s3am#18]
@hannes-ucsc I asked about this at one point and you said you thought `--resume` would basically do what I want (cancel pending transfer (if exists) / then upload), but when it encounters a a file that is not pending it does not upload it. 

I don't mind taking a look at this if your plate is full.

**Comment by hannes-ucsc** [comment]
`--resume` does not cancel uploads, it just resumes them. This is good as you don't have to start from scratch on every attempt. If you did have to start from scratch you could end up in a situation where you never get to the end. I think we should just remove the assertion that `--resume` expects something to be resumed. Feel free to take this on and file a PR.

**Comment by hannes-ucsc** [comment]
Resolved by b94c6f9528d0d80fdc256748b31c6ed48055be4a
