### ISSUE TITLE
Upload fails, and exception is thrown when printing error message

### ISSUE THREAD

**Issue by fnothaft** [BD2KGenomics/s3am#20]
I looked through the commits and issues and didn't see this elsewhere. There's a case where an upload fails, but then an exception is thrown when printing the error message describing why the upload failed.

I'd like to sort out the reason that the upload is failing, but for now, I'll just open a ticket with the error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/s3am", line 9, in <module>
    load_entry_point('s3am==1.0b1.dev49', 'console_scripts', 's3am')()
  File "/usr/local/lib/python2.7/dist-packages/s3am/cli.py", line 37, in try_main
    main( args )
  File "/usr/local/lib/python2.7/dist-packages/s3am/cli.py", line 74, in main
    result = operation.run( )
  File "/usr/local/lib/python2.7/dist-packages/s3am/operations.py", line 212, in run
    upload_id, completed_parts = self._prepare_upload( )
  File "/usr/local/lib/python2.7/dist-packages/s3am/operations.py", line 340, in _prepare_upload
    "incur storage fees.".format( me=me, **vars( self ) ) )
  File "/usr/lib/python2.7/contextlib.py", line 154, in __exit__
    self.thing.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

More details TBA in the AM.

**Comment by hannes-ucsc** [comment]
I can reproduce this when not specifying a URL as the first argument

```
s3am upload foo s3://foobar-bucket/foo
```

**Comment by fnothaft** [comment]
Perhaps it'd be good to sanity check that the input paths are both URL's? I can add that.

**Comment by hannes-ucsc** [comment]
I can also repro this with a full URL as the first argument. This issue is caused by the fact that the bucket is in the us-east-1 region. Working on a fix. The file vs URL thing should be in a follow-up issue.

**Comment by fnothaft** [comment]
Ah, gotcha! Thanks for catching this. If you're short on bandwidth, we can treat this as a won't fix for the moment, and I will move the bucket over to us-west-2 for now. We can then patch it at a later, more leisurely pace.

**Comment by hannes-ucsc** [comment]
It's ok. Will only take a few more minutes.

**Comment by fnothaft** [comment]
Sure, but I'll need to tear down the cluster, reinstall s3am from latest, etc, so it probably makes sense for me to work around the issue by moving the bucket.

**Comment by hannes-ucsc** [comment]
That's fine.

**Comment by hannes-ucsc** [comment]
http://jenkins.cgcloud.info/job/s3am/50/
https://pypi.python.org/pypi?:action=display&name=s3am&version=1.0b1.dev50
