### ISSUE TITLE
s3am download

### ISSUE THREAD

**Issue by dyollluap** [BD2KGenomics/s3am#60]
s3am within a toil-box image allows download but when installed separately on a generic ubuntu image or on a local machine it doesn't have the download function.

**Comment by arkal** [comment]
you need to install the --pre version

**Comment by mdperry** [comment]
Yes, this worked for me now when I installed the --pre version on a new VM.

**Comment by hschmidt** [comment]
Fixed with [2.0](https://github.com/BD2KGenomics/s3am/releases/tag/releases%2F2.0)
